client: client_main.c app_layer.c data_link_layer.c physical_layer.c
	gcc physical_layer.c data_link_layer.c app_layer.c client_main.c -o client -lrt -L/opt/lib.
#client: client.c socket_utilities.c
	#gcc -o client client.c socket_utilities.c -I.
