server: server_new.c server_utilities.c socket_utilities.c
	gcc -o server server_new.c server_utilities.c socket_utilities.c -I.
#client: client.c socket_utilities.c
	#gcc -o client client.c socket_utilities.c -I.
